### ISSUE TITLE
Compiling deepin-remote-assistance in macOS Sierra 10.12.4

### ISSUE THREAD

**Issue by cloorc** [linuxdeepin/deepin-remote-assistance#4]
# Steps

1. Install Qt 5;
2. Install Xcode;
3. Get source of [dtksettings](https://github.com/linuxdeepin/dtksettings), compile and install it according [README.md](https://github.com/linuxdeepin/dtksettings/blob/master/README.md);
4. Get source of [deepin-tool-kit](https://github.com/linuxdeepin/deepin-tool-kit), compile and install it locally;
5. Get source of [deepin-remote-assistant](), compile and install it;

## However, the first 3 steps maybe easy, the later two steps would not be as easy as the former 3.

First of all, I do not know why `pkgconfig` is not working on my mac os, so I disabled it and add proper package locations in `deepin-tool-kit/common/lib.pri` as following:

	LIB_INSTALL_DIR=/usr/local/lib
	INCLUDE_INSTALL_DIR=/usr/local/include
	LIBS += -L$$LIB_INSTALL_DIR -ldtksettings -ldtksettingsview
	INCLUDEPATH += $$INCLUDE_INSTALL_DIR/libdtk-1.0/DSettings $$INCLUDE_INSTALL_DIR/libdtk-1.0/DSettingsView

Then disable `pkgconfig` in project `dwidget/dwidget.pro` as following:

    macos{
        #CONFIG += link_pkgconfig
        #PKGCONFIG += dtksettings dtksettingsview
        #!system($$PWD/../tool/translate_generation.sh): error("Failed to generate translation")
    }

This will generate proper `Makefile` in `build/dwidget` and makes it work. Of course this is not the only one problem when compiling `deeping-tool-kit`, however, the solution is similar.

Time to compile our leading actor. Following the former idea, adding the locations of `dtkbase` as following:

    LIB_INSTALL_DIR=/usr/local/lib
    INCLUDE_INSTALL_DIR=/usr/local/include
    LIBS += -L$$LIB_INSTALL_DIR -ldtksettings -ldtksettingsview -ldtkbase -ldtkutil -ldtkwidget
    INCLUDEPATH += $$INCLUDE_INSTALL_DIR/libdtk-1.0/DSettings $$INCLUDE_INSTALL_DIR/libdtk-1.0/DSettingsView $$INCLUDE_INSTALL_DIR/libdtk-1.0/DBase $$INCLUDE_INSTALL_DIR/libdtk-1.0/DUtil $$INCLUDE_INSTALL_DIR/libdtk-1.0/DWidget

And never forget to disable `pkgconfig`:

    QT             += widgets dbus svg
    #QT             += widgets dbus x11extras svg
    #LIBS           += -lX11 -lXext
    #PKGCONFIG      += dtkbase dtkutil dtkwidget

Why do I disabled `X11`, `Xext` and `x11extras`? It is because I do not install these libraries and I do not think it's necessary. Ok, it's fine to compiling `deepin-remote-assistant`, and target `gui_port/deepin-remote-assistant.app` appears. However, it's too early to say it works well. When I double clicked the application, it shows me nothing but blank window. So depressing.

Could it because I disabled the `X*` libraries? This is the only factor I could imaging till now.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.

**Comment by cloorc** [comment]
> Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.

So I guess it had been solved already, was it right?
