### ISSUE TITLE
如果变成教学广播屏幕软件，方便吗？

### ISSUE THREAD

**Issue by bubifengyun** [linuxdeepin/deepin-remote-assistance#5]
看着这个远程协助，能够实现把远方的桌面，投到自己这里来。能否考虑把一台电脑的视频，投放给所有同一局域网的电脑？在 Linux 没有找到太好的软件。

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
